name: panhog
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - biopython
  - pyyaml
  - blast
  - mafft
  - pip:
    - panhog
